name: dependency-review

on:
  pull_request:
    branches: [main, master]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
